### ISSUE TITLE
NPE for Profile fetches

### ISSUE THREAD

**Issue by crankycoder** [crankycoder/fxa-android#8]
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.mozilla.accounts.fxa.tasks.ProfileJson.toString()' on a null object reference
1   at org.mozilla.accounts.fxa.tasks.base.AbstractSetDisplayNameTask.onPostExecute(AbstractSetDisplayNameTask.java:94)
2   at org.mozilla.accounts.fxa.tasks.base.AbstractSetDisplayNameTask.onPostExecute(AbstractSetDisplayNameTask.java:32)
3   at android.os.AsyncTask.finish(AsyncTask.java:632)
4   at android.os.AsyncTask.access$600(AsyncTask.java:177)
5   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
6   at android.os.Handler.dispatchMessage(Handler.java:102)
7   at android.os.Looper.loop(Looper.java:135)
8   at android.app.ActivityThread.main(ActivityThread.java:5254)
9   at java.lang.reflect.Method.invoke(Native Method)
10  at java.lang.reflect.Method.invoke(Method.java:372)
11  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
12  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
13  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

**Comment by crankycoder** [comment]
I'm going to just say that all bets are off with xposed.  The FxA android library hasn't had any significant problems for months on stock builds of android.
